### ISSUE TITLE
Hey!! I like to contribute to this project , Could I??

### ISSUE THREAD

**Issue by shivkushwaha1511** [ali-habibian/BookStoreWebsite#1]

**Comment by ali-habibian** [comment]
Hi
Yes you can

**Comment by ali-habibian** [comment]
Hi
Yes you can.

**Comment by shivkushwaha1511** [comment]
What can I do to contribute, please aware me of this project and tell me what contribution could I make, I'm well aware of JSP & Servlets and work on a project based on these tech stacks.
Waiting for your response!!
